"""
Six photographs of real paper, and what a person read off them.

Everything else in this corpus is rendered text with damage applied. That was
always the honest limit of it, stated in the README: it is a real test and it is
not paper. These are paper. Somebody held a camera over a till receipt, and the
creases, the dot-matrix ink, the aged thermal stock and the wood table under it
are all really there rather than simulated by a filter.

**The images are not in the repository.** They are freely licensed -- that was
the selection criterion, and the licence and author of each are recorded below
so attribution survives -- but several megabytes of JPEG in a repository whose
entire point is that it has no required dependencies would be a strange trade,
and mirroring somebody's photograph is not necessary when the URL is stable.
`python -m tests.corpus.photographs` fetches them; the tests skip, loudly, when
they are absent.

The truth was keyed by looking at each photograph and writing down the numbers
printed on it. That is the only way it can be done, and it is the reason this
file is worth more than the twenty-two rendered ones: nothing about it was
generated by the same process that is being tested.

Each entry carries what the paper says, and separately the numbers on it that
are *not* the receipt's arithmetic -- the cash tendered, the change, the
currency conversion. Those are the traps, and they are recorded because a
parser that reports the change as the total is wrong in the exact way this
project exists to catch.
"""
import hashlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DIRECTORY = os.path.join(HERE, "photographs")

#: `expect` is what is printed on the paper, in cents of whatever currency it
#: is in. A field that the receipt does not print is absent rather than zero.
#: `unreadable` marks a photograph no English-language engine should be able to
#: read, where the correct outcome is *unchecked* and any confident answer is a
#: failure.
PHOTOGRAPHS = [
    {
        "name": "png_vat_inclusive",
        "file": "store.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/c/cb/"
               "Receipt_from_the_store_%28PNG%29.jpg",
        "credit": "Receipt from the store (PNG).jpg — CC BY 4.0",
        "what": "Chin H. Meen & Son's, Lae. Flat on a blue desk mat, folded twice.",
        "expect": {"total": 1950, "tax": 177},
        "lines": [1950],
        # VAT is *inside* the total on this one -- "TOTAL INCLUDES VAT OF 1.77"
        # -- so subtotal + tax = total does not hold and must not be asserted.
        "tax_is_inclusive": True,
        "traps": {"cash tendered": 2000, "change": 50},
    },
    {
        "name": "swiss_restaurant",
        "file": "swiss.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/ReceiptSwiss.jpg",
        "credit": "ReceiptSwiss.jpg — CC BY-SA 3.0",
        "what": "Berghotel Grosse Scheidegg, on a wooden table, slight curl.",
        "expect": {"total": 5450, "tax": 385},
        "lines": [900, 500, 2200, 1850],
        "tax_is_inclusive": True,
        # The receipt prints its own total again in another currency. A parser
        # that takes the last number it sees gets 36.33.
        "traps": {"same total in euros": 3633},
    },
    {
        "name": "ddr_intershop_1988",
        "file": "ddr.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/3/35/"
               "Kassenbon_Intershop_Transit_Michendorf_DDR_1988.jpg",
        "credit": "Kassenbon Intershop Transit Michendorf DDR 1988.jpg — CC BY-SA 4.0",
        "what": "Dot-matrix on paper that has been folded since 1988. Heavily creased.",
        "expect": {"subtotal": 4900, "total": 4900},
        "lines": [4900],
        "traps": {"cash tendered (BAR)": 10000, "change (RUCK)": 5100},
    },
    {
        "name": "dutch_discount_no_total",
        "file": "top1toys.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/"
               "Top1Toys_receipt%2C_Oude_Pekela_%282020%29_05.jpg",
        "credit": "Top1Toys receipt, Oude Pekela (2020) 05.jpg — CC BY-SA 4.0",
        "what": "Photographed close, at an angle, in poor light. The total is "
                "off the bottom of the frame.",
        # Nothing here is a total. The right answer is to say so.
        "expect": {},
        "lines": [340],
        "unreadable": "the photograph does not include the total",
        "traps": {"a receipt number that looks like 20,000.696": None,
                  "the pre-discount price": 395},
    },
    {
        "name": "korean_restaurant",
        "file": "taebaek.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/7/76/"
               "Receipt_taebaek_restaurant_IMG_2614_modified.jpg",
        "credit": "Receipt taebaek restaurant IMG 2614 modified.jpg — public domain",
        "what": "Every label is in Hangul. The amounts are legible; the words "
                "naming them are not, to an English-language engine.",
        "expect": {},
        "unreadable": "the labels are in a script the engine was not given",
        "traps": {"a total of 76,000 with no English word anywhere near it": None},
    },
    {
        "name": "not_a_till_receipt",
        "file": "wikifood.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/5/56/"
               "Wikipedia_Receipt_For_Food.jpg",
        "credit": "Wikipedia Receipt For Food.jpg — CC0",
        "what": "A bank transfer confirmation, not a till receipt. It has one "
                "amount, no items, and nothing to crossfoot.",
        "expect": {},
        "unreadable": "there is no arithmetic on it to check",
        "traps": {"a phone number, an account number and a 12-digit reference":
                  None},
    },
]


def path_for(entry) -> str:
    return os.path.join(DIRECTORY, entry["file"])


def present() -> bool:
    return all(os.path.exists(path_for(entry)) for entry in PHOTOGRAPHS)


def fetch():                             # pragma: no cover - reaches the network
    """
    Download the six photographs from Wikimedia Commons.

    Deliberately not run by anything automatically, and not by the tests. This
    project's promise is that it does not reach the network while doing its job,
    and a test suite that quietly downloads several megabytes would be the first
    crack in that. Somebody runs this on purpose, once.
    """
    import urllib.request

    os.makedirs(DIRECTORY, exist_ok=True)
    for entry in PHOTOGRAPHS:
        target = path_for(entry)
        if os.path.exists(target):
            print(f"  have  {entry['file']}")
            continue
        request = urllib.request.Request(
            entry["url"], headers={"User-Agent": "crossfoot-corpus/0.1"})
        with urllib.request.urlopen(request, timeout=120) as response:
            data = response.read()
        with open(target, "wb") as handle:
            handle.write(data)
        digest = hashlib.sha256(data).hexdigest()[:16]
        print(f"  got   {entry['file']}  {len(data):,} bytes  sha256:{digest}")
        print(f"        {entry['credit']}")


if __name__ == "__main__":               # pragma: no cover - a person runs this
    fetch()
